nombre = input("Escriba su nombre: ")
print("Hola", nombre)
edad = int (input("Escriba su edad: "))
print(nombre, ", tu edad es: ", edad)
numero1 = (input("Escriba un numero: "))
print(nombre, ", el numero es: ", numero1) 
numero2 = (input("Escriba un segundo numero: "))
print(nombre, ", el numero es: ", numero2) 
Resul = (numero1+numero2)
print(nombre, ", ela suma de esos dos números es: ", Resul) 
num1 = int(input("Escriba otro numero: "))
print(nombre, ", el numero es: ", num1) 
num2 = int(input("Escriba un segundo numero: "))
print(nombre, ", el numero es: ", num2) 
Resul =(num1+num2)
#Resul =int(num1+num2) -- Comentarios
print(nombre, ", ela suma de esos dos números es: ", Resul) 
nume3 = float(input("Ingrese un número con decimales: "))
# Ejemplo: si ingresas "3.14159", numero3 = 3.14159
# Recordar que los decimales en python se expresan con puntos (.) no con comas (,)
print(f"{nume3:.5f}")
print("{:.3f}".format(nume3))
print(round (nume3,2))